### ISSUE TITLE
Creating an agent group fails

### ISSUE THREAD

**Issue by RandomAct5** [LittleLittleCloud/Multi-Agent-ChatUI#7]
When creating any group with any valid settings, when pressing save, it errors out with the following error.

"Application error: a client-side exception has occurred (see the browser console for more information)."

The following is the console output.

load from storage [index-33a356f7f1e71f8e.js:1:61938](http://localhost:3000/_next/static/chunks/pages/index-33a356f7f1e71f8e.js)
init [index-33a356f7f1e71f8e.js:1:62089](http://localhost:3000/_next/static/chunks/pages/index-33a356f7f1e71f8e.js)
add or update group 1 [index-33a356f7f1e71f8e.js:1:18738](http://localhost:3000/_next/static/chunks/pages/index-33a356f7f1e71f8e.js)
TypeError: d is undefined
    NextJS 64
[framework-73b8966a3c579ab0.js:9:69816](http://localhost:3000/_next/static/chunks/framework-73b8966a3c579ab0.js)
    NextJS 63
TypeError: d is undefined
    NextJS 64
[main-6260d066cf2cd7b1.js:1:10149](http://localhost:3000/_next/static/chunks/main-6260d066cf2cd7b1.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-6260d066cf2cd7b1.js:1:10166](http://localhost:3000/_next/static/chunks/main-6260d066cf2cd7b1.js)
    NextJS 65

**Comment by LittleLittleCloud** [comment]
@RandomAct5 Thanks for addressing this issue, I just pushed a fix. Newer version: 0.4.5
